# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under cicd_and_project/resources/*
# and cicd_and_project/databricks.yml with staging deployment target configs,
# when PRs are merged into the default branch
name: Bundle Deployment for cicd_and_project Staging

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./cicd_and_project

# env:
#  DATABRICKS_TOKEN: ${{ secrets.STAGING_WORKSPACE_TOKEN }}

jobs:
  staging:
    concurrency: cicd_and_project-staging-bundle-job
    runs-on: ubuntu-latest
    environment: DATABRICKS_TOKEN
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v0.221.0
      - name: Validate Bundle For Staging
        id: validate
        run: |
          databricks bundle validate -t staging
      - name: Deploy Bundle to Staging
        id: deploy
        run: |
          databricks bundle deploy -t staging
